name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TEST
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: TEST
        setup-command: ''
        command: javac ArrayStack.java && java ArrayStack
        input: |-
          2
          1
          1
          1
          2
          1
          3
          1
          4
          1
          5
          1
          6
          4
        expected-output: |-
          1.Push
          2.Pop
          3.Display Stack
          4.Exit

          Enter your choice:
          Stack is Underflow. No elements to be popped in Empty Stack

          1.Push
          2.Pop
          3.Display Stack
          4.Exit

          Enter your choice:
          Enter the element to insert:
          Element is inserted

          1.Push
          2.Pop
          3.Display Stack
          4.Exit

          Enter your choice:
          Enter the element to insert:
          Element is inserted

          1.Push
          2.Pop
          3.Display Stack
          4.Exit

          Enter your choice:
          Enter the element to insert:
          Element is inserted

          1.Push
          2.Pop
          3.Display Stack
          4.Exit

          Enter your choice:
          Enter the element to insert:
          Element is inserted

          1.Push
          2.Pop
          3.Display Stack
          4.Exit

          Enter your choice:
          Enter the element to insert:
          Element is inserted

          1.Push
          2.Pop
          3.Display Stack
          4.Exit

          Enter your choice:
          Enter the element to insert:
          Stack is Overflow. Not possible to insert in Full stack

          1.Push
          2.Pop
          3.Display Stack
          4.Exit

          Enter your choice:
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
